apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-dotnet60-basic-nfcp
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-dotnet60-basic-nfcp
    app.kubernetes.io/part-of: e2e-dotnet
  name: devfile-sample-dotnet60-basic-nfcp
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: devfile-dotnet-deploy
      app.kubernetes.io/instance: devfile-sample-dotnet60-basic-nfcp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: devfile-dotnet-deploy
        app.kubernetes.io/instance: devfile-sample-dotnet60-basic-nfcp
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-xnlj-tenant/e2e-dotnet/devfile-sample-dotnet60-basic-nfcp@sha256:a972f2ecf973acf5df6f8a89d7e6ffd35b756b653f2fb441639a81c90a481548
        imagePullPolicy: Always
        name: main
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
