apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-dotnet60-basic-nfcp
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-xnlj-tenant/e2e-dotnet/devfile-sample-dotnet60-basic-nfcp@sha256:a972f2ecf973acf5df6f8a89d7e6ffd35b756b653f2fb441639a81c90a481548
        name: main
        resources: {}
status: {}
